# application.yml
spring:
  datasource:
    url: jdbc:mysql://47.97.106.172:3306/ms?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "#ALiYun123"  # 注意yml中纯数字需要引号包裹

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  port: 8001  # 建议显式指定端口
  address: 0.0.0.0
